"""añadir_columna_eliminado_en_para_soft_delete

Revision ID: e2b3c42c9510
Revises: d115782f34d5
Create Date: 2026-08-21 13:19:57.136685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b3c42c9510'
down_revision: Union[str, Sequence[str], None] = 'd115782f34d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('eliminado_en', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'eliminado_en')
    # ### end Alembic commands ###
